### ISSUE TITLE
Allow checking output value contents using matchers (e.g. AssertJ matchers)

### ISSUE THREAD

**Issue by Zaijo** [bakdata/fluent-kafka-streams-tests#45]
Hello, thanks for the wrapper. Output values from my topics are rather big (containing many keys) and for the purpose of testing, I'd like to have a `#hasValueMatching(Predicate<V> predicate)` so that I don't need to construct full copies of my target objects to see some of the properties fulfilled.

Maybe there's something wrong with this need itself. I'd like to hear from you why that could possibly be a bad idea to test the values only partially. Thanks.

**Comment by philipp94831** [comment]
Hi @Zaijo , sorry for the late answer. You can always wrap the TestOutput with AssertJ. As it implements the Iterable interface, all assertions for iterables can be used. If you need multiple passes, you can create a List from it as you would do for any other Iterable. Does this help you? I would be cautious with adding many more methods to the output because it is hard to determine where to stop and increases maintenance effort.

**Comment by Zaijo** [comment]
Thanks. That could work.
