### ISSUE TITLE
Support JsonSchema and Protobuf providers on SchemaRegistryMock

### ISSUE THREAD

**Issue by sergialonsaco** [bakdata/fluent-kafka-streams-tests#50]
Since confluent version 5.5.0, schema registry supports JsonSchema and Protobuf as SchemaProviders to register schemas on it. To do so, when creating a SchemaRegistryClient or MockSchemaRegistryClient, a list of providers can be passed and it will use those ones for the registry.

The problem happens to be that in your TestTopology and SchemaRegistryMock classes, there is no support to send a list of providers to the MockSchemaRegistry you internally use.

Can anyone help me with that?

**Comment by torbsto** [comment]
Hi, I've opened a corresponding PR. However, I'm not sure whether I handle all cases correctly, especially regarding the schema references, since I haven't worked much with the new API yet. I'd appreciate any feedback.
You can clone the repository, switch to the `feature/schema-provider` branch and run `./gradlew publishToMavenLocal`. This will allow you to use version `2.3.1-SNAPSHOT` with the applied changes.
[This test](https://github.com/bakdata/fluent-kafka-streams-tests/blob/343f18eb0471bd4fb254cb17fe4a10b2b4bddd79/schema-registry-mock/src/test/java/com/bakdata/schemaregistrymock/ProtobufRegistryMockTest.java) shows an example using schema provider.

**Comment by sergialonsaco** [comment]
Hi @torbsto, so many thanks for your help! Appreciate that. 
I just did a [small PR](https://github.com/bakdata/fluent-kafka-streams-tests/pull/52) to your branch, as for me it would be nice if when creating a TestTopology, the list of SchemaProviders could be given, and that list will be used on the SchemaRegistryMock that you modified. Does it make sense to you?

**Comment by sergialonsaco** [comment]
Awesome @torbsto, indeed it makes more sense to use the `wither`. Thanks for the update!
